spring:
  datasource:
    url: jdbc:mysql://mysql-azmaan1311-20cb.i.aivencloud.com:24655/defaultdb?createTableIfNotExists=true
    username: avnadmin
    password: AVNS_NnBD7r1TJBwgRDYSU9J
  data:
    redis:
      host: redis-19994.crce206.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 19994
      password: 8FTaFPkvKAAr4nBF7b1SrEsP2b0GNoFp
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: smtp.gmail.com
    port: 587
    username: azmaan000@gmail.com
    password: vitikdvnfvnclybk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    consumer:
      bootstrap-servers: localhost:9092
      group-id: ticketflix-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true

# JWT Configuration
jwt:
  secret: YourSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLongForHS512AlgorithmToWorkProperlyAndSecurely
  expiration: 86400000 # 24 hours in milliseconds